### ISSUE TITLE
PKB not checking for existence of element before accessing it

### ISSUE THREAD

**Issue by freesoup** [CS3203-Team-6/SPA#70]
~~Error in fRelationship where u dereference next when there is no next.~~

This occurs in source1.txt when query is made to PKB to find the follower of line 12.
As line 12 is the only statement in the while statement list, it has no follows relationship and was not added into the followsTable in FollowStorage. When queried, PKB did not check for its existence before finding it in the table.

**Comment by randypx** [comment]
I will add a check to all getter functions
