### ISSUE TITLE
PKB allowing adding new Follow* to list.

### ISSUE THREAD

**Issue by freesoup** [CS3203-Team-6/SPA#73]
I think for example given that the list of Follow*(a, b)

If in the follow* relation, given a is 1 and b is 2, 3, 4, 5, 6, 7

Allow adding 8 to an already present list.

**Comment by randypx** [comment]
To rephrase your issue,
Currently PKB only allows the PostProcessor/ Design Extractor to set the list of direct/indirect followers of a given statement once. And it should allow individual additions.

Was wondering why you wanted this. My idea was that by not allowing additions, it would better serve to encapsulate the data in PKB and lower the chance of any false entry. This is not a bug, so it'll not be a priority.
